# Generated by Django 3.0.7 on 2020-06-27 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conn_string', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.IntegerField(db_index=True)),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='sales.DataOrigin')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ext_id', models.IntegerField(db_index=True)),
                ('data_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='sales.DataOrigin')),
            ],
            options={
                'unique_together': {('data_origin', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ext_id', models.IntegerField(db_index=True)),
                ('data_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='sales.DataOrigin')),
            ],
            options={
                'unique_together': {('data_origin', 'name')},
            },
        ),
    ]
